/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login/": {
    /**
     * Takes a set of user credentials and returns an access and refresh JSON web
     * token pair to prove the authentication of those credentials.
     */
    post: operations["auth_login_create"];
    parameters: {};
  };
  "/auth/register/": {
    post: operations["auth_register_create"];
    parameters: {};
  };
  "/auth/token/refresh/": {
    /**
     * Takes a refresh type JSON web token and returns an access type JSON web
     * token if the refresh token is valid.
     */
    post: operations["auth_token_refresh_create"];
    parameters: {};
  };
  "/auth/token/verify/": {
    /**
     * Takes a token and indicates if it is valid.  This view provides no
     * information about a token's fitness for a particular use.
     */
    post: operations["auth_token_verify_create"];
    parameters: {};
  };
  "/dm/{username}/": {
    get: operations["dm_read"];
    parameters: {
      path: {
        username: string;
      };
    };
  };
}

export interface definitions {
  TokenObtainPair: {
    email: string;
    password: string;
  };
  RegisterUser: {
    email: string;
    username: string;
    password: string;
  };
  TokenRefresh: {
    refresh: string;
  };
  TokenVerify: {
    token: string;
  };
  DirectMessage: {
    uuid?: string;
  };
}

export interface operations {
  /**
   * Takes a set of user credentials and returns an access and refresh JSON web
   * token pair to prove the authentication of those credentials.
   */
  auth_login_create: {
    parameters: {
      body: {
        data: definitions["TokenObtainPair"];
      };
    };
    responses: {
      201: {
        schema: definitions["TokenObtainPair"];
      };
    };
  };
  auth_register_create: {
    parameters: {
      body: {
        data: definitions["RegisterUser"];
      };
    };
    responses: {
      201: {
        schema: definitions["RegisterUser"];
      };
    };
  };
  /**
   * Takes a refresh type JSON web token and returns an access type JSON web
   * token if the refresh token is valid.
   */
  auth_token_refresh_create: {
    parameters: {
      body: {
        data: definitions["TokenRefresh"];
      };
    };
    responses: {
      201: {
        schema: definitions["TokenRefresh"];
      };
    };
  };
  /**
   * Takes a token and indicates if it is valid.  This view provides no
   * information about a token's fitness for a particular use.
   */
  auth_token_verify_create: {
    parameters: {
      body: {
        data: definitions["TokenVerify"];
      };
    };
    responses: {
      201: {
        schema: definitions["TokenVerify"];
      };
    };
  };
  dm_read: {
    parameters: {
      path: {
        username: string;
      };
    };
    responses: {
      200: {
        schema: definitions["DirectMessage"];
      };
    };
  };
}

export interface external {}
